In [1]:
import numpy as np
print("NumPy Version:", np.__version__)
print("\nNumPy Build Configuration:")
np.show_config()

NumPy Version: 1.26.4

NumPy Build Configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/NV_User/anaconda3/Library/include
    lib directory: C:/Users/NV_User/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
  

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
result = np.all(arr != 0)
print("Array:", arr)
print("None of the elements are zero:", result)

Array: [1 2 3 4 5]
None of the elements are zero: True


In [3]:
import numpy as np
arr = np.array([0, 0, 0, 5, 0])
result = np.any(arr != 0)
print("Array:", arr)
print("Any non-zero elements:", result)

Array: [0 0 0 5 0]
Any non-zero elements: True


In [4]:
import numpy as np
arr = np.array([1, 0, np.nan, np.inf, -np.inf, 5.5])
result = np.isfinite(arr)
print("Original Array:", arr)
print("Finiteness Check:", result)

Original Array: [ 1.   0.   nan  inf -inf  5.5]
Finiteness Check: [ True  True False False False  True]


In [5]:
import numpy as np
arr = np.array([1.0, np.inf, -np.inf, np.nan, 0.0, 5.5])
result = np.isinf(arr)
print("Original Array:", arr)
print("Infinity Check (±inf):", result)

Original Array: [ 1.   inf -inf  nan  0.   5.5]
Infinity Check (±inf): [False  True  True False False False]


In [6]:
import numpy as np
arr = np.array([np.nan, 1.0, 0.0, np.inf, -np.inf, np.nan])
result = np.isnan(arr)
print("Original Array:", arr)
print("NaN Check:", result)

Original Array: [ nan   1.   0.  inf -inf  nan]
NaN Check: [ True False False False False  True]


In [7]:
import numpy as np

a = np.array([3, 5, 2, 7])
b = np.array([4, 5, 1, 8])

greater = np.greater(a, b)
greater_equal = np.greater_equal(a, b)
less = np.less(a, b)
less_equal = np.less_equal(a, b)

print("Array a:", a)
print("Array b:", b)
print("\na > b :", greater)
print("a >= b:", greater_equal)
print("a < b :", less)
print("a <= b:", less_equal)

Array a: [3 5 2 7]
Array b: [4 5 1 8]

a > b : [False False  True False]
a >= b: [False  True  True False]
a < b : [ True False False  True]
a <= b: [ True  True False  True]


In [8]:
import numpy as np

a = np.array([1.0, 2.0, 3.000001, 4.0])
b = np.array([1.0, 2.0, 3.0, 5.0])

exact_equal = np.equal(a, b)

tolerance_equal = np.isclose(a, b, atol=1e-5)

print("Array a:", a)
print("Array b:", b)
print("\nExact equality (a == b):", exact_equal)
print("Equality within tolerance (a ≈ b):", tolerance_equal)

Array a: [1.       2.       3.000001 4.      ]
Array b: [1. 2. 3. 5.]

Exact equality (a == b): [ True  True False False]
Equality within tolerance (a ≈ b): [ True  True  True False]


In [9]:
import numpy as np

zeros_array = np.zeros(10)
ones_array = np.ones(10)
fives_array = np.full(10, 5)

print("Array of 10 zeros:", zeros_array)
print("Array of 10 ones:", ones_array)
print("Array of 10 fives:", fives_array)

Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives: [5 5 5 5 5 5 5 5 5 5]


In [10]:
import numpy as np
arr = np.arange(30, 71)
print("Array of integers from 30 to 70:", arr)

Array of integers from 30 to 70: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [11]:
import numpy as np
even_arr = np.arange(30, 71, 2)
print("Even integers from 30 to 70:", even_arr)

Even integers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [12]:
import numpy as np
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:")
print(identity_matrix)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
import numpy as np
random_number = np.random.rand()
print("Random number between 0 and 1:", random_number)

Random number between 0 and 1: 0.048634662341801915


In [14]:
import numpy as np
vector = np.arange(15, 56)
print("Original vector:", vector)
print("Values except first and last:", vector[1:-1])

Original vector: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
Values except first and last: [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [15]:
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)
print("3x4 Array:")
print(arr)
print("\nIterating over elements:")
for row in arr:
    for element in row:
        print(element, end=' ')
    print()  

3x4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Iterating over elements:
1 2 3 4 
5 6 7 8 
9 10 11 12 


In [16]:
import numpy as np
vector = np.linspace(5, 50, 10)
print("Vector with evenly spaced values between 5 and 50:")
print(vector)

Vector with evenly spaced values between 5 and 50:
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [17]:
import numpy as np
vector = np.arange(21)
mask = (vector >= 9) & (vector <= 15)
vector[mask] = -vector[mask]
print("Modified vector:")
print(vector)

Modified vector:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [18]:
import numpy as np
vector1 = np.array([1, 2, 3, 4])
vector2 = np.array([5, 6, 7, 8])

result = vector1 * vector2

print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Element-wise multiplication:", result)

Vector 1: [1 2 3 4]
Vector 2: [5 6 7 8]
Element-wise multiplication: [ 5 12 21 32]


In [19]:
import numpy as np
arr = np.arange(10, 22).reshape(3, 4)
print("3x4 matrix filled with values from 10 to 21:")
print(arr)

3x4 matrix filled with values from 10 to 21:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [20]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

rows, columns = matrix.shape

print("Number of rows:", rows)
print("Number of columns:", columns)

Number of rows: 4
Number of columns: 3


In [21]:
import numpy as np
matrix = np.zeros((5, 5), dtype=int)
np.fill_diagonal(matrix, [1, 2, 3, 4, 5])
print("5x5 matrix with diagonal elements 1 to 5:")
print(matrix)

5x5 matrix with diagonal elements 1 to 5:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [22]:
import numpy as np
arr = np.random.rand(3, 3, 3)
print("3x3x3 array with arbitrary values:")
print(arr)

3x3x3 array with arbitrary values:
[[[0.82783406 0.42069079 0.1058087 ]
  [0.00583679 0.61067894 0.25764994]
  [0.15867295 0.36127387 0.23218735]]

 [[0.40432465 0.78893618 0.78277043]
  [0.52762859 0.99728019 0.13579278]
  [0.79836052 0.39632882 0.57317614]]

 [[0.80693846 0.77812802 0.0542758 ]
  [0.85260079 0.83811054 0.46156712]
  [0.33696346 0.43880316 0.06243994]]]


In [23]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

total_sum = np.sum(arr)
col_sum = np.sum(arr, axis=0)
row_sum = np.sum(arr, axis=1)

print("Array:")
print(arr)
print("\nSum of all elements:", total_sum)
print("Sum of each column:", col_sum)
print("Sum of each row:", row_sum)

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of all elements: 45
Sum of each column: [12 15 18]
Sum of each row: [ 6 15 24]


In [24]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

inner_product = np.dot(vector1, vector2)

print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Inner product:", inner_product)

Vector 1: [1 2 3]
Vector 2: [4 5 6]
Inner product: 32


In [25]:
import numpy as np

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

vector = np.array([1, 0, 1, 0])
result = matrix + vector

print("Original matrix:\n", matrix)
print("Vector to add:", vector)
print("Result after adding vector to each row:\n", result)

Original matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Vector to add: [1 0 1 0]
Result after adding vector to each row:
 [[ 2  2  4  4]
 [ 6  6  8  8]
 [10 10 12 12]]


In [26]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1, 2, 3, 4])
arr3 = np.array([1, 2, 0, 4])

equal_all = np.array_equal(arr1, arr2)
not_equal_all = np.array_equal(arr1, arr3)
elementwise_equal = np.equal(arr1, arr3)

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Array 3:", arr3)
print("\nAre arr1 and arr2 exactly equal?", equal_all)
print("Are arr1 and arr3 exactly equal?", not_equal_all)
print("Element-wise equality between arr1 and arr3:", elementwise_equal)

Array 1: [1 2 3 4]
Array 2: [1 2 3 4]
Array 3: [1 2 0 4]

Are arr1 and arr2 exactly equal? True
Are arr1 and arr3 exactly equal? False
Element-wise equality between arr1 and arr3: [ True  True False  True]


In [27]:
import numpy as np
arr = np.zeros((5, 6), dtype=float)
print("Array of shape (5,6) filled with zeros:")
print(arr)
print("Data type:", arr.dtype)

Array of shape (5,6) filled with zeros:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Data type: float64


In [28]:
import numpy as np
arr = np.array([[9, 2, 7],
                [4, 5, 6],
                [3, 8, 1]])

print("Original array:")
print(arr)
row_sorted = np.sort(arr, axis=1)

print("\nArray sorted by rows (each row sorted ascending):")
print(row_sorted)
col_sorted = np.sort(arr, axis=0)
print("\nArray sorted by columns (each column sorted ascending):")
print(col_sorted)

Original array:
[[9 2 7]
 [4 5 6]
 [3 8 1]]

Array sorted by rows (each row sorted ascending):
[[2 7 9]
 [4 5 6]
 [1 3 8]]

Array sorted by columns (each column sorted ascending):
[[3 2 1]
 [4 5 6]
 [9 8 7]]


In [29]:
import numpy as np
arr = np.array([10, 25, 5, 30, 15, 40, 2, 50])
num = 20
less_than = arr[arr < num]
greater_than = arr[arr > num]
print("Original array:", arr)
print(f"Numbers less than {num}:", less_than)
print(f"Numbers greater than {num}:", greater_than)

Original array: [10 25  5 30 15 40  2 50]
Numbers less than 20: [10  5 15  2]
Numbers greater than 20: [25 30 40 50]


In [30]:
import numpy as np
arr = np.array([10, 25, 5, 30, 15, 40, 2, 50])
num = 20
result = arr.copy()
result[result == num] = -1
result[result < num] = 0
result[result > num] = 1
print("Original array:", arr)
print("Modified array:", result)

Original array: [10 25  5 30 15 40  2 50]
Modified array: [0 1 0 1 0 1 0 1]


In [31]:
import numpy as np
arr = np.arange(1, 17).reshape(4, 4)
print("Original array:")
print(arr)
swapped_arr = arr[:, [3, 2, 1, 0]]
print("\nArray after swapping columns:")
print(swapped_arr)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Array after swapping columns:
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [32]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original array:")
print(arr)
reversed_arr = arr[::-1, ::-1]

print("\nArray with rows and columns swapped in reverse order:")
print(reversed_arr)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array with rows and columns swapped in reverse order:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [33]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
result = arr1 * arr2
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Element-wise multiplication:", result)

Array 1: [1 2 3 4]
Array 2: [5 6 7 8]
Element-wise multiplication: [ 5 12 21 32]


In [34]:
import numpy as np
num_list = [12.23, 13.32, 100, 36.32]
num_array = np.array(num_list)
print("Original list:", num_list)
print("Converted NumPy array:", num_array)

Original list: [12.23, 13.32, 100, 36.32]
Converted NumPy array: [ 12.23  13.32 100.    36.32]


In [35]:
import numpy as np
matrix = np.arange(2, 11).reshape(3, 3)
print("3x3 Matrix with values from 2 to 10:")
print(matrix)

3x3 Matrix with values from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [36]:
import numpy as np
vector = np.zeros(10)
vector[5] = 11
print("Updated vector:")
print(vector)

Updated vector:
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [37]:
import numpy as np
array = np.arange(12, 39)
print("Array from 12 to 38:")
print(array)

Array from 12 to 38:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [39]:
import numpy as np
array = np.arange(1, 38)  
print("Original array:")
print(array)

reversed_array = array[::-1]
print("Reversed array:")
print(reversed_array)

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reversed array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [40]:
import numpy as np
arr = np.array([1, 2, 3, 4])
float_arr = arr.astype(float)
print("Original array:", arr)
print("Array converted to float:", float_arr)

Original array: [1 2 3 4]
Array converted to float: [1. 2. 3. 4.]


In [42]:
import numpy as np
arr = np.array([10, 20, 30])
values_to_append = [40, 50, 60, 70, 80, 90]
new_arr = np.append(arr, values_to_append)
print("Original array:", arr)
print("Array after appending:", new_arr)

Original array: [10 20 30]
Array after appending: [10 20 30 40 50 60 70 80 90]


In [44]:
import numpy as np
empty_array = np.empty((3, 4))
full_array = np.full((3, 3), 6)
print(empty_array)
print(full_array)

[[1.01855798e-312 1.12465777e-312 1.01855798e-312 9.54898106e-313]
 [1.03977794e-312 1.01855798e-312 1.23075756e-312 1.16709769e-312]
 [1.03977794e-312 9.76118064e-313 1.12465777e-312 1.90979621e-312]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [48]:
import numpy as np

fahrenheit_values = np.array([0, 12, 45.21, 34, 99.91, 32.])
centigrade_values = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0.])

converted_to_fahrenheit = centigrade_values * 9 / 5 + 32

converted_to_centigrade = (fahrenheit_values - 32) * 5 / 9

print("Values in Fahrenheit degrees:", fahrenheit_values)
print("Values in Centigrade degrees:", centigrade_values)
print("Values in Centigrade degrees:", centigrade_values)
print("Values in Fahrenheit degrees:", converted_to_fahrenheit)

Values in Fahrenheit degrees: [ 0.   12.   45.21 34.   99.91 32.  ]
Values in Centigrade degrees: [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Values in Centigrade degrees: [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Values in Fahrenheit degrees: [-4.0000e-03  1.2002e+01  4.5212e+01  3.3998e+01  9.9914e+01  3.2000e+01]


In [49]:
import numpy as np

array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([0, 40])

comparison = np.isin(array1, array2)

print("Array1:", array1)
print("Array2:", array2)
print("Compare each element of array1 and array2", comparison)

Array1: [ 0 10 20 40 60]
Array2: [ 0 40]
Compare each element of array1 and array2 [ True False False  True False]


In [50]:
import numpy as np

array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])

common_values = np.intersect1d(array1, array2)

print("Array1:", array1)
print("Array2:", array2)
print("Common values between two arrays:", common_values)

Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Common values between two arrays: [10 40]


In [51]:
import numpy as np

arr1 = np.array([10, 10, 20, 20, 30, 30])
unique_arr1 = np.unique(arr1)

print("Original array:")
print(arr1)
print("Unique elements of the above array:", unique_arr1)

arr2 = np.array([[1, 1],
                 [2, 3]])
unique_arr2 = np.unique(arr2)

print("\nOriginal array:")
print(arr2)
print("Unique elements of the above array:", unique_arr2)

Original array:
[10 10 20 20 30 30]
Unique elements of the above array: [10 20 30]

Original array:
[[1 1]
 [2 3]]
Unique elements of the above array: [1 2 3]


In [52]:
import numpy as np

array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70, 90])

set_diff = np.setdiff1d(array1, array2)

print("Array1:", array1)
print("Array2:", array2)
print("Set difference between two arrays:", set_diff)

Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70 90]
Set difference between two arrays: [ 0 20 60 80]


In [53]:
import numpy as np

a = np.array([1, 2])
b = np.array([4, 5])

gt = a > b
ge = a >= b
lt = a < b
le = a <= b

print("Array a:", a)
print("Array b:", b)
print("a > b", gt)
print("a >= b", ge)
print("a < b", lt)
print("a <= b", le)

Array a: [1 2]
Array b: [4 5]
a > b [False False]
a >= b [False False]
a < b [ True  True]
a <= b [ True  True]


In [54]:
import numpy as np
arr = np.array([[4, 6], [2, 1]])
print("Original array:")
print(arr)
sorted_first_axis = np.sort(arr, axis=0)
print("\nSort along the first axis:")
print(sorted_first_axis)
sorted_last_axis = np.sort(arr, axis=1)
print("\nSort along the last axis:")
print(sorted_last_axis)

Original array:
[[4 6]
 [2 1]]

Sort along the first axis:
[[2 1]
 [4 6]]

Sort along the last axis:
[[4 6]
 [1 2]]


In [55]:
import numpy as np
arr = np.array([[0, 10, 20], [20, 30, 40]])
indices = np.where(arr > 10)

values = arr[indices]

print("Original array:")
print(arr)
print("Values bigger than 10 =", values)
print("Their indices are", indices)

Original array:
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [56]:
import numpy as np
a = np.array([[10, 20, 30], [20, 40, 50]])
print("Original array:")
print(a)

flat = a.ravel()
print("New flattened array:")
print(flat)

Original array:
[[10 20 30]
 [20 40 50]]
New flattened array:
[10 20 30 20 40 50]


In [57]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]], dtype=np.int32)

print("Shape:", arr.shape)
print("Type:", type(arr))
print("Data type:", arr.dtype)

Shape: (2, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


In [58]:
import numpy as np
original_array = np.array([[1, 2],
                           [3, 4],
                           [5, 6]])

reshaped_array = original_array.reshape(2, 3)

print("Original 3x2 array:\n", original_array)
print("Reshaped 2x3 array:\n", reshaped_array)

Original 3x2 array:
 [[1 2]
 [3 4]
 [5 6]]
Reshaped 2x3 array:
 [[1 2 3]
 [4 5 6]]


In [60]:
import numpy as np
array = np.full((3, 5), 2)
print(array)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [61]:
import numpy as np
original_array = np.array([1, 2, 3, 4])
tens_array = np.full_like(original_array, 10)
print(tens_array)

[10 10 10 10]


In [62]:
import numpy as np
diagonal_values = [4, 5, 6, 8]
array = np.diag(diagonal_values)
print(array)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]


In [63]:
import numpy as np
array1 = np.arange(0, 50)
print("Array from 0 to 50:")
print(array1)

array2 = np.arange(10, 50)
print("Array from 10 to 50:")
print(array2)

Array from 0 to 50:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
Array from 10 to 50:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [64]:
import numpy as np
arr = np.array([[2, 4, 6],
                [6, 8, 10]])

print("Original array:")
print(arr)
fourth_element = arr.flatten()[3]
print("Forth element of the array:", fourth_element)

Original array:
[[ 2  4  6]
 [ 6  8 10]]
Forth element of the array: 6


In [65]:
import numpy as np
arr = np.array([[1.12, 2.0, 3.45],
                [2.33, 5.12, 6.0]])

test_values = [1.12, 7, 3.45, 8, 5.12]

presence = [val in arr for val in test_values]

print("Original array:")
print(arr)
print(*presence)

Original array:
[[1.12 2.   3.45]
 [2.33 5.12 6.  ]]
True False True False True
