In [1]:
import numpy as np
arr = np.array([[0, 1],
                [2, 3]])

print("Original flattened array:")
print(arr)

flat_arr = arr.flatten()

max_val = flat_arr.max()
min_val = flat_arr.min()

print("Maximum value of the above flattened array:", max_val)
print("Minimum value of the above flattened array:", min_val)

Original flattened array:
[[0 1]
 [2 3]]
Maximum value of the above flattened array: 3
Minimum value of the above flattened array: 0


In [2]:
import numpy as np
arr = np.array([[0, 1],
                [2, 3]])

print("Original array:")
print(arr)

max_along_axis = np.max(arr, axis=1)
min_along_axis = np.min(arr, axis=1)

print("Maximum value along the second axis:", max_along_axis)
print("Minimum value along the second axis:", min_along_axis)

Original array:
[[0 1]
 [2 3]]
Maximum value along the second axis: [1 3]
Minimum value along the second axis: [0 2]


In [3]:
import numpy as np
arr = np.array([[0, 1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10, 11]])

print("Original array:")
print(arr)

diff = np.max(arr, axis=1) - np.min(arr, axis=1)

print("Difference between the maximum and the minimum values of the said array:", diff)

Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Difference between the maximum and the minimum values of the said array: [5 5]


In [4]:
import numpy as np
arr = np.array([[1.0, 2.0, 3.0, 4.0],
                [5.0, 6.0, 7.0, 8.0]])

print("Original array:")
print(arr)

percentile_80 = np.percentile(arr, 80, axis=1)

print("80th percentile along the second axis:")
print(percentile_80)

Original array:
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
80th percentile along the second axis:
[3.4 7.4]


In [5]:
import numpy as np
arr = np.array([[0, 1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10, 11]])

print("Original array:")
print(arr)

median_value = np.median(arr.flatten())

print("Median of said array:", median_value)

Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Median of said array: 5.5


In [6]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4])
weights = np.array([1, 2, 3, 4, 5])
weighted_avg = np.average(arr, weights=weights)

print("Original array:", arr)
print("Weighted average of the said array:", weighted_avg)

Original array: [0 1 2 3 4]
Weighted average of the said array: 2.6666666666666665


In [7]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5])
print("Original array:", arr)

mean_val = np.mean(arr)
std_val = np.std(arr)
var_val = np.var(arr)

print("Mean:", mean_val)
print("Std:", std_val)
print("Variance:", var_val)

Original array: [0 1 2 3 4 5]
Mean: 2.5
Std: 1.707825127659933
Variance: 2.9166666666666665


In [8]:
import numpy as np
array1 = np.array([0, 1, 2])
array2 = np.array([2, 1, 0])

print("Original array1:", array1)
print("Original array2:", array2)

data = np.vstack((array1, array2))

cov_matrix = np.cov(data)

print("Covariance matrix of the said arrays:")
print(cov_matrix)

Original array1: [0 1 2]
Original array2: [2 1 0]
Covariance matrix of the said arrays:
[[ 1. -1.]
 [-1.  1.]]


In [9]:
import numpy as np

array1 = np.array([0, 1, 3])
array2 = np.array([2, 4, 5])

print("Original array1:", array1)
print("Original array2:", array2)

cross_corr = np.correlate(array1, array2)

print("Cross-correlation of the said arrays:", cross_corr)

Original array1: [0 1 3]
Original array2: [2 4 5]
Cross-correlation of the said arrays: [19]


In [10]:
import numpy as np

array1 = np.array([0, 1, 3])
array2 = np.array([2, 4, 5])

print("Original array1:", array1)
print("Original array2:", array2)

data = np.vstack((array1, array2))

corr_matrix = np.corrcoef(data)

print("Pearson product-moment correlation coefficients of the said arrays:")
print(corr_matrix)

Original array1: [0 1 3]
Original array2: [2 4 5]
Pearson product-moment correlation coefficients of the said arrays:
[[1.         0.92857143]
 [0.92857143 1.        ]]


In [11]:
import numpy as np

arr = np.array([np.inf, 5, np.nan])
arr_datetime = np.array(['NaT', '2023-01-01'], dtype='datetime64')

print("Test element-wise for finiteness (not infinity or not Not a Number):", 
      np.isfinite(arr))

print("Test element-wise for positive or negative infinity:", 
      np.isinf(arr))

print("Test element-wise for NaN:", 
      np.isnan(arr))

print("Test element-wise for NaT (not a time):", 
      np.isnat(arr_datetime))

inf_arr = np.array([-np.inf, 0, np.inf])

print("Test element-wise for negative infinity:", 
      (inf_arr == -np.inf).astype(int))

print("Test element-wise for positive infinity:", 
      (inf_arr == np.inf).astype(int))


Test element-wise for finiteness (not infinity or not Not a Number): [False  True False]
Test element-wise for positive or negative infinity: [ True False False]
Test element-wise for NaN: [False False  True]
Test element-wise for NaT (not a time): [ True False]
Test element-wise for negative infinity: [1 0 0]
Test element-wise for positive infinity: [0 0 1]


In [12]:
import numpy as np
arr = np.array([0, 1, 6, 1, 4, 1, 2, 2, 7])

print("Original array:", arr)

counts = np.bincount(arr)

print("Number of occurrences of each value in array:", counts)

Original array: [0 1 6 1 4 1 2 2 7]
Number of occurrences of each value in array: [1 3 2 0 1 0 1 1]


In [13]:
import numpy as np

nums = np.array([0.5, 0.7, 1.0, 1.2, 1.3, 2.1])
bins = np.array([0, 1, 2, 3])

print("nums:", nums)
print("bins:", bins)

hist, bin_edges = np.histogram(nums, bins=bins)

print("Result:", (hist, bin_edges))

nums: [0.5 0.7 1.  1.2 1.3 2.1]
bins: [0 1 2 3]
Result: (array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))
